name: Bug report
description: Report a problem with cfx-api
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report a bug.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A minimal code snippet that reproduces the issue.
      render: javascript
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: cfx-api version
      placeholder: 2.0.1
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: 20.x
    validations:
      required: true
