name: ESLint

on: [push, pull_request]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install ESLint
        run: npm ci

      - name: Run ESLint
        run: npm run lint
